use_frameworks!

platform :ios, '8.0'

target 'QLAlertViewController_Example' do
  pod 'QLAlertViewController', :path => '../'

  target 'QLAlertViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
